### ISSUE TITLE
Comment Link on Standard Post Format

### ISSUE THREAD

**Issue by DustinWStout** [jbrad/standard-bootstrap-3#2]
It seems as if the standard post format doesn't display a comments link. I discovered this as I was trying to fix another issue-- the permalink icon is a Glyphicon on some post formats, and the standard permalink icon on other post formats.

**Comment by jbrad** [comment]
I am seeing the comments link just fine on my demo site http://jasonbradley.me/standard-child-themes/standard-bootstrap-3/

Have you made some changes to the child theme?
